name: intelligent_food_delivery
version: 1.0.0+1
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  google_fonts: ^2.3.2
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.1.0
  firebase_core: ^1.19.1
  firebase_auth: ^3.4.1
  firebase_storage: ^10.3.1
  flutter_statusbarcolor_ns: ^0.4.0
  cloud_firestore_odm: ^1.0.0-dev.21
  cloud_firestore: ^3.3.0
  get_storage: ^2.0.3
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  in_app_review: ^2.0.4
  flutter_svg: ^1.1.1+1
  permission_handler: ^10.0.0
  sizer: ^2.0.15
  freezed_annotation: ^1.1.0
  json_annotation: ^4.6.0
  meta: ^1.3.0
  image_picker: ^0.8.5+3
  animations: ^2.0.3
  chips_choice_null_safety: ^2.0.6
  buildcondition: ^0.0.4
  intl: ^0.17.0
  custom_pop_up_menu: ^1.2.4
  double_back_to_close_app: ^2.1.0
  cached_network_image: ^3.2.1
  otp_text_field: ^1.1.3
  dropdown_search: ^5.0.2
  group_button: ^5.0.1
  google_maps_flutter: ^2.1.12
  location: ^4.4.0
  get: 4.6.5
  flutter: 
    sdk: flutter
  fade_shimmer: ^2.0.1
  chips_input: ^0.1.0

dev_dependencies: 
  build_runner: ^2.2.0
  cloud_firestore_odm_generator: ^1.0.0-dev.21
  json_serializable: ^6.3.0
  flutter_gen_runner: ^4.3.0
  flutter_lints: ^2.0.1
  flutter_test: 
    sdk: flutter

dependency_overrides: 
  image_picker_android: 0.8.4+13

flutter_gen: 
  output: lib/assets/
  integrations: 
    flutter_svg: true
  line_length: 80

flutter: 
  assets: 
    - assets/svg/
    - assets/
    - assets/images/
    - assets/icons/
  uses-material-design: true

